# Header
menu:
  Blog: /#blog
  About: /about
  #归档: /archive
  Links: /links

# Site favicon
favicon: /images/favicon.ico

# Site logo
logo: /images/avatar.png

# Enable Mathjax
mathjax: true

# Enable awesome-toc
awesome_toc: true

# Enable githubRepoWidget
github_repo_widget: false
