# Header
menu:
  Blog: /#blog
  About: /about
  #归档: /archive
  Links: /links

# Site favicon
favicon: /images/favicon.ico

# Site logo
logo: /images/avatar.png

# Enable Mathjax
mathjax: true

# Enable fancybox
fancybox: true

# Enable githubRepoWidget
github_repo_widget: false

# Enable BaiduPush
baidupush: false

# Date / Time format
date_time_format: YYYY-MM-DD HH:mm:ss